TARGET = tedori_hw5p1a
GRAPH = tedori_hw5p1b
CC = mpic++
CVER = -std=c++11

default: $(TARGET).cpp
	$(CC) $(CVER) $(TARGET).cpp -o $(TARGET)

graph: $(GRAPH).cpp
	$(CC) $(CVER) $(GRAPH).cpp -o $(GRAPH)
