CC = mpic++
TARGET = tedori_hw4p2a
TARGET2 = tedori_hw4p2b
CVER = -std=c++11
default: $(TARGET).cpp
	$(CC) $(CVER) $(TARGET).cpp -o $(TARGET)

binchunk: $(TARGET2).cpp
	$(CC) $(CVER) $(TARGET2).cpp -o $(TARGET2)
